can delete archived
amida-tech/amida-messaging-microservice pull request #25
Opened 2017-12-05 18:15 UTC by ElijahGeorge

If this PR fixes a bug, you _must_ add test cases representative of the bug.
#### What's this PR do?
Allows message owner to soft-delete archived messages
#### Related JIRA tickets: https://jira.amida-tech.com/browse/SER-106
#### How should this be manually tested?
#### Any background context you want to provide?
#### Screenshots (if appropriate):

2017-12-05 19:14 UTC, jsachs requested changes
This looks correct. Can we add tests to make sure that (1) it works for both unarchive and delete, and (2) we can actually delete an archived message?

2017-12-05 19:14 UTC, jsachs commented on server/controllers/message.controller.js
> +  return unscopedRoutes.find(route => url.includes(route)) != undefined;
Use `!==` instead.

2017-12-05 19:15 UTC, ElijahGeorge commented on server/controllers/message.controller.js
> +  return unscopedRoutes.find(route => url.includes(route)) != undefined;
👍

2017-12-05 19:16 UTC, ElijahGeorge commented on server/controllers/message.controller.js
> +  return unscopedRoutes.find(route => url.includes(route)) != undefined;
Good catch

2017-12-07 20:05 UTC, jsachs approved these changes

2017-12-07 20:08 UTC, sirctseb approved these changes

2017-12-07 22:37 UTC, merged