Logging updates
amida-tech/amida-messaging-microservice pull request #63
Opened 2018-08-24 20:46 UTC by puckybreg

If this PR fixes a bug, you _must_ add test cases representative of the bug.
#### What's this PR do?
Updates Winston & adds swagger-stats to the API
#### Related JIRA tickets:
https://jira.amida-tech.com/browse/ORANGE-625
#### How should this be manually tested?
#### Any background context you want to provide?
#### Screenshots (if appropriate):

2018-09-18 16:28 UTC, orndorffgrant commented
It looks like there is another logger enabled in `config/express.js:23` called `morgan`. Should we remove this so that we only have nice winston json logging?

Otherwise the winston logging and swagger stats worked for me!

2018-09-19 14:17 UTC, puckybreg commented
@orndorffgrant Yeah, it's interesting, both `winston` & `morgan` existed in the project before I did these updates. My best guess is that they are used for different types of logging? At least in the console when running this service I don't see duplicate logging.

2018-09-19 15:28 UTC, orndorffgrant commented
When I run `yarn start` I am seeing double logging
![screen shot 2018-09-19 at 11 16 32 am](https://user-images.githubusercontent.com/5448265/45762999-9e320b80-bbfd-11e8-9bc4-fbfb8f5ccda0.png)
(Notice the json logging for the 401s and then the prettier human readable colored 401 messages below them)

When I comment out `morgan` I don't get the prettier lines of logging.

So I think we should either get rid of `morgan`, or keep `morgan` on during development and only turn `winston` on for production

2018-09-19 15:32 UTC, orndorffgrant commented
Also, (sorry I keep noticing more things), it looks like there is already an actuator in there. See `config/express.js:61`

If you hit `/actuator/metrics` you get metrics for this service. This is redundant now that we have swagger stats right? So we should probably strip out this actuator as well?

2018-09-21 16:57 UTC, puckybreg commented
This PR has been updated

2018-09-21 17:04 UTC, orndorffgrant commented
There are some actuator tests in server/tests/misc.spec.js that could be modified to test the new swagger endpoints in a basic fashion if you're up to it, or we can just delete them for now.

2018-09-21 17:35 UTC, orndorffgrant approved these changes
👍

2018-09-21 17:35 UTC, puckybreg commented
oof, you got me again @orndorffgrant. I think I found a compromise between fixing and removing the tests. Swagger-Stats doesn't have a endpoint just for info on the app (or at least not one that is obvious on the Swagger-Stats docs).

2018-09-27 23:18 UTC, rmharrison requested changes
Please turn-off non-JSON debug logging in production.

2018-09-27 23:18 UTC, rmharrison commented on index.js
>  const debug = require('debug')('amida-api-boilerplate:index');
## Immediate recommendation (blocking)
- Disable debug logging in production
- Right now, debug logging (e.g. postgres), happens for both production and development environments to stdout. 
- Why: All logging in stdout (at least in prod) should be JSON structured

Confirm with
```
$ work@Hargrove:~/git/amida-tech/amida-messaging-microservice (logging-updates)$ NODE_ENV='production' yarn start
...
Executing (default): CREATE TABLE IF NOT EXISTS "Users" ("id"  SERIAL , "username" VARCHAR(255) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'Users' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
```

## Next step
May want to discuss what to do with non-JSON structured debug logging in development.
While turning-off in prod is within the scope of this PR, there could be some debate about what to do in dev.
I'm inclined towards **always JSON**, with folks separating the prettification-concern, but the community seems split. From what I can tell, Winston folks bake prettificiation into the application for debug, while bunyan folks prettify seperately (all JSON in both prod and dev). YMMV.

2018-09-27 23:18 UTC, rmharrison commented on index.js
> +                message: `server started on port ${config.port} (${config.env})`,
**Non-blocking**
`config.port` and `config.env` are perfect candidates for log keys. Agnostic about punting to https://jira.amida.com/browse/ORANGE-795 when the log format will be updated anyways.

2018-09-27 23:18 UTC, rmharrison commented on config/express.js
>  // enable detailed API logging in dev env
Update comment, or update code?

2018-10-09 21:42 UTC, rmharrison approved these changes
**Blocking item (logging SQL in PROD) resolved in pairing.**

NB: Dev formatter hasn't been updated to show structured log items
```
$ NODE_ENV='development' yarn start

2018-10-09T21:35:09.401Z info: server started on port
```

```
$ NODE_ENV='production' yarn start

{"service":"messaging-service","message":"server started on port","port":4001,"node_env":"production","level":"info"}
```

2018-10-09 21:42 UTC, rmharrison commented on config/sequelize.js
> +    dbLogging = (msg) => logger.debug(msg);
Resolves immediate concern around logging raw sequel in PROD.

2018-10-09 21:42 UTC, rmharrison commented on index.js
> +      if (err) logger.debug('An error occured', err);
NB: Doesn't look like you've configured winston to error formatting ==> `err = new Error()` object will not actually log.

2018-10-09 21:45 UTC, rmharrison commented
** 2-cents / personal preference **
I would have rebased `branch:logging-updates` to tip of `branch:develop` instead of merging at 881a3d7.

![selection_029](https://user-images.githubusercontent.com/4275722/46700459-eb950d80-cbea-11e8-8d16-4a34b4c6c897.png)

2018-10-10 18:14 UTC, orndorffgrant approved these changes
Approved again

2018-10-10 18:40 UTC, merged