Making test scripts self sufficient
amida-tech/amida-messaging-microservice pull request #64
Opened 2018-09-04 14:04 UTC by dbrezack

If this PR fixes a bug, you _must_ add test cases representative of the bug.
#### What's this PR do?
Adds .env.test for use in testing environment 
Creates database on testing and starting of the app.
Fixes issue with tests not working the first time
#### Related JIRA tickets:
https://jira.amida-tech.com/browse/SER-228
https://jira.amida-tech.com/browse/SER-222
#### How should this be manually tested?
run `yarn build`
create `.env.test` file
change the db name in `.env.test` file
run `yarn create_db`
run `yarn test` verify it FAILS 
run `yarn delete_db`
run `yarn test` verify it works

#### Any background context you want to provide?
#### Screenshots (if appropriate):

2018-09-05 15:47 UTC, mountHouli approved these changes

2018-09-24 15:50 UTC, orndorffgrant requested changes
Found an inconsistency between this and the other micros - the postgres pw in this one is stored as `config.postgres.passwd` instead of `config.postgres.password`.
The other micros use `password` so we should probably update this one to match

2018-09-24 18:27 UTC, dbrezack commented
@orndorffgrant passwd was changed to password

2018-09-24 18:31 UTC, orndorffgrant approved these changes
Thanks!

2018-09-24 18:32 UTC, merged