Feature/add UUID
amida-tech/amida-messaging-microservice pull request #69
Opened 2018-10-09 21:19 UTC by nickmccally

If this PR fixes a bug, you _must_ add test cases representative of the bug.

#### What's this PR do?

Check if uuids are missing from user documents. Add uuid for users, where missing, from auth service. If one does not exist on auth, one will be generated by orange-api. 
 
#### Related JIRA tickets:

- https://jira.amida.com/browse/ORANGE-481

#### How should this be manually tested?

Run `yarn && yarn start`. You should run this *AFTER* you have already started the auth service on the branch that has uuid support. 

#### Any background context you want to provide?

Support new microservices using uuid versus username (which is typically registration email)

2018-10-10 19:52 UTC, ElijahGeorge reviewed
Added some comments pertaining to minor changes. LGTM

2018-10-10 19:52 UTC, ElijahGeorge commented on package.json
> +    "request": "false2.88.0",
@nickmccally I think we can remove the `false`. It seems to be a yarn bug

2018-10-10 19:52 UTC, ElijahGeorge commented on package.json
> +    "request-promise": "false4.2.2",
dito

2018-10-10 20:43 UTC, ElijahGeorge requested changes
Everything looks good to me except the `false` in `package.json`.

2018-10-11 15:16 UTC, ElijahGeorge approved these changes

2018-10-12 17:17 UTC, mountHouli approved these changes
It worked for me. I dropped my messaging DB and created a new one from scratch, then tested sharing two users logs and sent a message.

2018-10-12 17:17 UTC, merged